name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message and Set Version
        id: vars
        run: |
          if [[ "${{ github.event.head_commit.message }}" == major:* ]]; then
            echo "::set-output name=version_type::major"
          elif [[ "${{ github.event.head_commit.message }}" == minor:* ]]; then
            echo "::set-output name=version_type::minor"
          elif [[ "${{ github.event.head_commit.message }}" == fix:* ]]; then
            echo "::set-output name=version_type::patch"
          else
            echo "::set-output name=version_type::skip"
          fi

      - name: Bump version and push tag
        if: steps.vars.outputs.version_type != 'skip'
        uses: anothrNick/github-tag-action@1.64.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.vars.outputs.version_type }}

      - name: Create a Release
        if: steps.vars.outputs.version_type != 'skip'
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release ${{ github.ref }}
