name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: git fetch --force --tags

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - run: echo "version='${{ env.GITHUB_REF_NAME }}'" >> gradle.properties

      - name: Build Jar
        run: ./gradlew shadowJar --no-daemon

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: ${{ env.GITHUB_REF_NAME }}
          prerelease: false
          files: |
            build/libs/uk-invitation-letter-${{ env.GITHUB_REF_NAME }}.jar