name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run Tests
        run: ./gradlew test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message and Set Version
        id: version
        run: |
          if [[ "${{ github.event.head_commit.message }}" == major:* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == minor:* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == patch:* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "type=skip" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        if: steps.version.outputs.type != 'skip'
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ steps.vars.outputs.version_type }}

      - name: Create a Release
        if: steps.version.outputs.type != 'skip'
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release ${{ github.ref }}
